// Client-Vite/src/components/FurnitureDetails.tsx
import { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import type { Furniture } from '../models/furniture';
import { furnitureService } from '../services/furnitureService';
import styles from './FurnitureDetails.module.css';

const FurnitureDetails = () => {
  const [furniture, setFurniture] = useState<Furniture | null>(null);
  const [loading, setLoading] = useState(true);
  const { id } = useParams<{ id: string }>();

  useEffect(() => {
    if (id) {
      furnitureService.getFurniture(parseInt(id))
        .then((response) => {
          setFurniture(response.data);
          setLoading(false);
        })
        .catch((error) => {
          console.error('Error fetching furniture details:', error);
          setLoading(false);
        });
    }
  }, [id]);

  if (loading) {
    return (
      <div className="container">
        <div className="text-center">Loading...</div>
      </div>
    );
  }

  if (!furniture) {
    return (
      <div className="container">
        <div className="text-center">
          <p>Furniture not found</p>
        </div>
      </div>
    );
  }

  return (
    <div className="container">
      <div className="row space-top">
        <div className="col-md-12">
          <h1>Furniture Details</h1>
        </div>
      </div>
      
      {furniture && (
        <div className="row space-top">
          <div className="col-md-4">
            <div className="card text-white bg-primary">
              <div className="card-body">
                <blockquote className="card-blockquote">
                  <img src={furniture.image} alt={`${furniture.make} ${furniture.model}`} className={styles.img} />
                </blockquote>
              </div>
            </div>
          </div>
          <div className="col-md-4">
            <p>Make: {furniture.make}</p>
            <p>Model: {furniture.model}</p>
            <p>Year: {furniture.year}</p>
            <p>Description: {furniture.description}</p>
            <p>Price: {furniture.price}</p>
            {furniture.material && (
              <p>Material: {furniture.material}</p>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default FurnitureDetails;

// Client/src/app/furniture/furniture-details/furniture-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { FurnitureService } from '../furniture.service';
import { Furniture } from '../../models/furniture';


@Component({
    selector: 'app-furniture-details',
    imports: [],
    templateUrl: './furniture-details.component.html',
    styleUrl: './furniture-details.component.css'
})
export class FurnitureDetailsComponent implements OnInit {
  furniture: Furniture;

  constructor(private route: ActivatedRoute, private furnitureService: FurnitureService) {
  }

  ngOnInit(): void {
    this.route.params.subscribe((data) => {
      let id = data['id'];
      this.furnitureService.getFurniture(id).subscribe(data => {
        this.furniture = data;
      });
    });
  }
}

<div class="container">
  <div class="row space-top">
    <div class="col-md-12">
      <h1>Furniture Details</h1>
    </div>
  </div>
  @if (furniture) {
    <div class="row space-top">
      <div class="col-md-4">
        <div class="card text-white bg-primary">
          <div class="card-body">
            <blockquote class="card-blockquote">
              <img src="{{furniture.image}}" />
            </blockquote>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <p>Make: {{furniture.make}}</p>
        <p>Model: {{furniture.model}}</p>
        <p>Year: {{furniture.year}}</p>
        <p>Description: {{furniture.description}}</p>
        <p>Price: {{furniture.price}}</p>
        @if (furniture.material) {
          <p>Material: {{furniture.material}}</p>
        }
      </div>
    </div>
  }
</div>
