// Client/src/app/furniture/create-edit-furniture/create-edit-furniture.component.ts

import { Component, OnInit } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { FurnitureService } from '../furniture.service';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-create-furniture',
  imports: [ReactiveFormsModule],
  templateUrl: './create-edit-furniture.component.html',
  styleUrl: './create-edit-furniture.component.css'
})
export class CreateEditFurnitureComponent implements OnInit {
  id: number;
  form: any;
  loading: boolean;

  constructor(
    private route: ActivatedRoute,
    private fb: FormBuilder,
    private furnitureService: FurnitureService,
    private router: Router) {
  }

  ngOnInit(): void {
    this.loading = true;
    this.form = this.fb.group({
      id: [0],
      make: ['', [Validators.required, Validators.minLength(4)]],
      model: ['', [Validators.required, Validators.minLength(4)]],
      year: [0, [Validators.required, Validators.min(1950), Validators.max(2050)]],
      description: ['', [Validators.required, Validators.minLength(10)]],
      price: [0, [Validators.required, Validators.min(0)]],
      image: ['', [Validators.required]],
      material: ['']
    });

    this.route.params.subscribe((data) => {
      this.id = data['id'];
      if (this.id) {
        this.furnitureService.getFurniture(this.id).subscribe({
          next: (data) => {
            this.form.patchValue(data);
            this.loading = false;
          },
          error: () => {
            this.loading = false;
          }
        });
      }
    });
  }

  createFurniture() {
    console.log(this.form);
    this.furnitureService.createFurniture(this.form.value).subscribe((data) => {
      this.router.navigate(['/furniture/all'])
    });
  }

  editFurniture() {
    console.log(this.form);
    this.furnitureService.editFurniture(this.id, this.form.value).subscribe((data) => {
      this.router.navigate(['/furniture/all'])
    });
  }

  get f() {
    return this.form.controls;
  }
}

<div class="container">
  <div class="row space-top">
    <div class="col-md-12">
      @if (!id) {
      <h1>Create New Furniture</h1>
      }
      @if (id) {
      <h1>Edit Existing Furniture</h1>
      }
      @if (loading) {
      <div className="text-center">Loading...</div>
      }
      @else {
      <p>Please fill all fields.</p>
      }
    </div>
  </div>
  @if (!loading) {
  <form [formGroup]="form" (submit)="!id ? createFurniture() : editFurniture()">
    <div class="row space-top">
      <div class="col-md-4">
        <div class="form-group">
          <label class="form-control-label" for="new-make">Make</label>
          <input class="form-control" id="new-make" type="text" formControlName="make">
          @if (f.make.touched && f.make.errors?.required) {
          <div class="alert alert-danger">
            This field is required
          </div>
          }
          @if (f.make.touched && f.make.errors?.minlength) {
          <div class="alert alert-danger">
            Length must be at least {{f.make.errors?.minlength.requiredLength}} chars
          </div>
          }
        </div>

        <div class="form-group has-success">
          <label class="form-control-label" for="new-model">Model</label>
          <input class="form-control is-valid" id="new-model" type="text" formControlName="model">
          @if (f.model.touched && f.model.errors?.required) {
          <div class="alert alert-danger">
            This field is required
          </div>
          }
          @if (f.model.touched && f.model.errors?.minlength) {
          <div class="alert alert-danger">
            Length must be at least {{f.model.errors?.minlength.requiredLength}} chars
          </div>
          }
        </div>

        <div class="form-group has-danger">
          <label class="form-control-label" for="new-year">Year</label>
          <input class="form-control is-invalid" id="new-year" type="number" formControlName="year">
          @if (f.year.touched && f.year.errors?.required) {
          <div class="alert alert-danger">
            This field is required
          </div>
          }
          @if (f.year.touched && f.year.errors?.min) {
          <div class="alert alert-danger">
            Year must start from {{f.year.errors?.min.min}}
          </div>
          }
          @if (f.year.touched && f.year.errors?.max) {
          <div class="alert alert-danger">
            Year must be below {{f.year.errors?.max.max}}
          </div>
          }
        </div>

        <div class="form-group">
          <label class="form-control-label" for="new-description">Description</label>
          <input class="form-control" id="new-description" type="text" formControlName="description">
          @if (f.description.touched && f.description.errors?.required) {
          <div class="alert alert-danger">
            This field is required
          </div>
          }
          @if (f.description.touched && f.description.errors?.minlength) {
          <div class="alert alert-danger">
            Length must be at least {{f.description.errors?.minlength.requiredLength}} chars
          </div>
          }
        </div>
      </div>
      <div class="col-md-4">
        <div class="form-group">
          <label class="form-control-label" for="new-price">Price</label>
          <input class="form-control" id="new-price" type="number" formControlName="price">
          @if (f.price.touched && f.price.errors?.required) {
          <div class="alert alert-danger">
            This field is required
          </div>
          }
          @if (f.price.touched && f.price.errors?.min) {
          <div class="alert alert-danger">
            Min value must be: {{f.price.errors?.min.min}}
          </div>
          }
        </div>

        <div class="form-group">
          <label class="form-control-label" for="new-image">Image</label>
          <input class="form-control" id="new-image" type="text" formControlName="image">
          @if (f.image.touched && f.image.errors?.required) {
          <div class="alert alert-danger">
            This field is required
          </div>
          }
        </div>

        <div class="form-group">
          <label class="form-control-label" for="new-material">Material (optional)</label>
          <input class="form-control" id="new-material" type="text" formControlName="material">
        </div>
        @if (!id) {
        <button type="submit" class="btn btn-primary" [disabled]="form.invalid">Create</button>
        }
        @if (id) {
        <button type="submit" class="btn btn-primary" [disabled]="form.invalid">Edit</button>
        }
      </div>
    </div>
  </form>
  }
</div>

// Client-Vite/src/components/CreateEditFurniture.tsx
import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router';
import { Formik, Form, Field, ErrorMessage } from 'formik';
import * as Yup from 'yup';
import type { Furniture } from '../models/furniture';
import { furnitureService } from '../services/furnitureService';
import styles from './CreateEditFurniture.module.css';

const validationSchema = Yup.object({
  make: Yup.string()
    .required('This field is required')
    .min(4, 'Length must be at least 4 chars'),
  model: Yup.string()
    .required('This field is required')
    .min(4, 'Length must be at least 4 chars'),
  year: Yup.number()
    .required('This field is required')
    .min(1950, 'Year must start from 1950')
    .max(2050, 'Year must be below 2050'),
  description: Yup.string()
    .required('This field is required')
    .min(10, 'Length must be at least 10 chars'),
  price: Yup.number()
    .required('This field is required')
    .min(0, 'Min value must be: 0'),
  image: Yup.string()
    .required('This field is required'),
  material: Yup.string()
});

const CreateEditFurniture = () => {
  const [loading, setLoading] = useState(false);
  const [initialValues, setInitialValues] = useState<Furniture>({
    id: 0,
    make: '',
    model: '',
    year: 0,
    description: '',
    price: 0,
    image: '',
    material: ''
  });
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();

  useEffect(() => {
    if (id) {
      setLoading(true);
      furnitureService.getFurniture(parseInt(id))
        .then((response) => {
          setInitialValues(response.data);
          setLoading(false);
        })
        .catch(() => {
          setLoading(false);
        });
    }
  }, [id]);

  const handleSubmit = (values: Furniture) => {
    if (id) {
      furnitureService.editFurniture(parseInt(id), values)
        .then(() => {
          navigate('/furniture/all');
        });
    }
    else {
      furnitureService.createFurniture(values)
        .then(() => {
          navigate('/furniture/all');
        });
    }
  };

  return (
    <div className="container">
      <div className="row space-top">
        <div className="col-md-12">
          <h1>{id ? 'Edit Existing Furniture' : 'Create New Furniture'}</h1>
          {loading ? (
            <div className="text-center">Loading...</div>
          ) : (
            <p>Please fill all fields.</p>
          )}
        </div>
      </div>
      {!loading && (
        <Formik
          initialValues={initialValues}
          validationSchema={validationSchema}
          onSubmit={handleSubmit}
          enableReinitialize={true}
        >
          {({ isValid }) => (
            <Form>
              <div className="row space-top">
                <div className="col-md-4">
                  <div className="form-group">
                    <label className="form-control-label" htmlFor="new-make">Make</label>
                    <Field
                      className="form-control"
                      id="new-make"
                      type="text"
                      name="make"
                    />
                    <ErrorMessage name="make">
                      {msg => <div className="alert alert-danger">{msg}</div>}
                    </ErrorMessage>
                  </div>

                  <div className="form-group">
                    <label className="form-control-label" htmlFor="new-model">Model</label>
                    <Field
                      className="form-control"
                      id="new-model"
                      type="text"
                      name="model"
                    />
                    <ErrorMessage name="model">
                      {msg => <div className="alert alert-danger">{msg}</div>}
                    </ErrorMessage>
                  </div>

                  <div className="form-group">
                    <label className="form-control-label" htmlFor="new-year">Year</label>
                    <Field
                      className="form-control"
                      id="new-year"
                      type="number"
                      name="year"
                    />
                    <ErrorMessage name="year">
                      {msg => <div className="alert alert-danger">{msg}</div>}
                    </ErrorMessage>
                  </div>

                  <div className="form-group">
                    <label className="form-control-label" htmlFor="new-description">Description</label>
                    <Field
                      className="form-control"
                      id="new-description"
                      type="text"
                      name="description"
                    />
                    <ErrorMessage name="description">
                      {msg => <div className="alert alert-danger">{msg}</div>}
                    </ErrorMessage>
                  </div>
                </div>

                <div className="col-md-4">
                  <div className="form-group">
                    <label className="form-control-label" htmlFor="new-price">Price</label>
                    <Field
                      className="form-control"
                      id="new-price"
                      type="number"
                      name="price"
                    />
                    <ErrorMessage name="price">
                      {msg => <div className="alert alert-danger">{msg}</div>}
                    </ErrorMessage>
                  </div>

                  <div className="form-group">
                    <label className="form-control-label" htmlFor="new-image">Image</label>
                    <Field
                      className="form-control"
                      id="new-image"
                      type="text"
                      name="image"
                    />
                    <ErrorMessage name="image">
                      {msg => <div className="alert alert-danger">{msg}</div>}
                    </ErrorMessage>
                  </div>

                  <div className="form-group">
                    <label className="form-control-label" htmlFor="new-material">Material (optional)</label>
                    <Field
                      className="form-control"
                      id="new-material"
                      type="text"
                      name="material"
                    />
                  </div>

                  <button
                    type="submit"
                    className={`btn btn-primary ${styles.button}`}
                    disabled={!isValid}
                  >
                    {id ? 'Edit' : 'Create'}
                  </button>
                </div>
              </div>
            </Form>
          )}
        </Formik>
      )}
    </div>
  );
};

export default CreateEditFurniture;
