// Client/src/app/furniture/furniture-all/furniture-all.component.ts
import { Component, OnInit } from '@angular/core';
import { Furniture } from '../../models/furniture';
import { FurnitureService } from '../furniture.service';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { AuthService } from '../../authentication/auth.service';

@Component({
    selector: 'app-furniture-all',
    imports: [CommonModule, RouterLink],
    templateUrl: './furniture-all.component.html',
    styleUrl: './furniture-all.component.css'
})
export class FurnitureAllComponent implements OnInit {
  furnitures: Furniture[]
  isUserAdmin: boolean;

  constructor(private furnitureService: FurnitureService, private authService: AuthService) {
  }

  ngOnInit(): void {
    this.getAllFurnitures();
    this.isUserAdmin = this.authService.getUserFromToken().roles[0] === 'Super Admin';
  }

  getAllFurnitures() {
    setTimeout(() => {
      this.furnitureService.getAllFurnitures().subscribe((data: any) => {
        this.furnitures = data.items;
      });
    }, 1000);
  }

  deleteFurniture(id: number) {
    this.furnitureService.deleteFurniture(id).subscribe((data) => {
      this.getAllFurnitures();
    });
  }
}
<div class="container">
    <div class="row space-top">
        <div class="col-md-12">
            <h1>Welcome to Furniture System</h1>
            <p>Select furniture from the catalog to view details.</p>
        </div>
    </div>

    <ng-template [ngIf]="!furnitures">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4 text-center">Loading...</div>
            <div class="col-md-4"></div>
        </div>
    </ng-template>

    <ng-template [ngIf]="furnitures && furnitures.length === 0">
        <div class="row space-top">
            <div class="col-md-12">
                No furnitures
            </div>
        </div>
    </ng-template>

    <ng-template [ngIf]="furnitures && furnitures.length > 0">
        <div class="row space-top">
            <div class="col-md-4" *ngFor="let f of furnitures">
                <div class="card text-white bg-primary">
                    <div class="card-body">
                        <blockquote class="card-blockquote">
                            <img src="{{f.image}}" />
                            <p>{{f.description | slice:0:11 }}...</p>
                            <div class="pull-right">
                                <a [routerLink]="['/furniture/details/', f.id]" class="btn btn-info">Details</a>
                                <a [routerLink]="['/furniture/edit/', f.id]" class="btn btn-info"
                                    *ngIf="isUserAdmin">Edit</a>
                                <a (click)="deleteFurniture(f.id)" class="btn btn-danger" *ngIf="isUserAdmin">Delete</a>
                            </div>
                        </blockquote>
                    </div>
                </div>
            </div>
        </div>
    </ng-template>
</div>

// Client-Vite/src/components/FurnitureAll.tsx
import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import type { Furniture } from '../models/furniture';
import { furnitureService } from '../services/furnitureService';
import { authService } from '../services/authService';
import styles from './FurnitureAll.module.css';

const FurnitureAll = () => {
  const [furnitures, setFurnitures] = useState<Furniture[]>([]);
  const [loading, setLoading] = useState(true);
  const [isUserAdmin, setIsUserAdmin] = useState(false);

  useEffect(() => {
    getAllFurnitures();
    const user = authService.getUserFromToken();
    setIsUserAdmin(user.roles[0] === 'Super Admin');
  }, []);

  const getAllFurnitures = () => {
    setLoading(true);
    let timer = setTimeout(() => {
      furnitureService.getAllFurnitures()
        .then((response) => {
          const data = response.data;
          setFurnitures(Array.isArray(data) ? data : data.items);
          setLoading(false);
        })
        .catch(() => {
          setLoading(false);
        });
    }, 1000);

    return () => {
      clearTimeout(timer);
    }
  };

  const deleteFurniture = (id: number) => {
    furnitureService.deleteFurniture(id)
      .then(() => {
        getAllFurnitures();
      });
  };

  return (
    <div className="container">
      <div className="row space-top">
        <div className="col-md-12">
          <h1>Welcome to Furniture System</h1>
          <p>Select furniture from the catalog to view details.</p>
        </div>
      </div>

      {loading && (
        <div className="row">
          <div className="col-md-4"></div>
          <div className="col-md-4 text-center">Loading...</div>
          <div className="col-md-4"></div>
        </div>
      )}

      {!loading && furnitures.length === 0 ? (
        <div className="row space-top">
          <div className="col-md-12">
            No furnitures
          </div>
        </div>
      ) : (
        <div className="row space-top">
          {furnitures.map((furniture) => (
            <div key={furniture.id} className="col-md-4">
              <div className="card text-white bg-primary">
                <div className={`card-body ${styles.cardBody}`}>
                  <blockquote className={`card-blockquote ${styles.blockquote}`}>
                    <img src={furniture.image} alt={`${furniture.make} ${furniture.model}`} className={styles.img} />
                    <p>{furniture.description.length > 11
                      ? `${furniture.description.slice(0, 11)}...`
                      : furniture.description
                    }</p>
                    <div className="pull-right">
                      <Link
                        to={`/furniture/details/${furniture.id}`}
                        className={`btn btn-info ${styles.btnInfo}`}
                      >
                        Details
                      </Link>
                      {isUserAdmin && (
                        <Link
                          to={`/furniture/edit/${furniture.id}`}
                          className={`btn btn-info ${styles.btnInfo}`}
                        >
                          Edit
                        </Link>
                      )}
                      {isUserAdmin && (
                        <a
                          onClick={() => deleteFurniture(furniture.id)}
                          className="btn btn-danger"
                        >
                          Delete
                        </a>
                      )}
                    </div>
                  </blockquote>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default FurnitureAll;
