// Client/src/app/navigation/navigation.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '../authentication/auth.service';

import { DropdownDirective } from './dropdown.directive';
import { CollapseDirective } from './collapse.directive';

@Component({
    selector: 'app-navigation',
    templateUrl: './navigation.component.html',
    styleUrls: ['./navigation.component.css'],
    imports: [RouterModule, DropdownDirective, CollapseDirective]
})
export class NavigationComponent implements OnInit {
  constructor(
    public authService: AuthService,
    private router: Router
  ) {  }

  ngOnInit() {
  }

  logout() {
    this.authService.logout();
    
    this.router.navigate([ '/signin' ]);
  }
}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" routerLink="/home">Furniture Store</a>
  <button appCollapse class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor01"
    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-collapse collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      @if (!authService.isAuthenticated()) {
        <li class="nav-item">
          <a class="nav-link" routerLink="/signin">Sign In</a>
        </li>
      }
      @if (!authService.isAuthenticated()) {
        <li class="nav-item">
          <a class="nav-link" routerLink="/signup">Sign Up</a>
        </li>
      }
      @if (authService.isAuthenticated()) {
        <li class="nav-item">
          <a class="nav-link" (click)="logout()">Logout</a>
        </li>
      }
      @if (authService.isAuthenticated()) {
        <li appNavDropdown class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Store</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" routerLink="/furniture/all">All Furniture</a>
            <a class="dropdown-item" routerLink="/furniture/user">My Furniture</a>
            <a class="dropdown-item" routerLink="/furniture/create">Create</a>
          </div>
        </li>
      }
    </ul>
  </div>
</nav>

// Client-Vite/src/components/Navigation.tsx
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { authService } from '../services/authService';

const Navigation = () => {
  const [isCollapsed, setIsCollapsed] = useState(true);
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
  const navigate = useNavigate();

  const toggleCollapse = () => {
    setIsCollapsed(!isCollapsed);
  };

  const toggleDropdown = () => {
    setIsDropdownOpen(!isDropdownOpen);
  };

  const logout = () => {
    authService.logout();
    navigate('/signin');
  };

  return (
    <nav className="navbar navbar-expand-lg navbar-dark bg-primary">
      <Link className="navbar-brand" to="/home">Furniture Store</Link>
      <button 
        className="navbar-toggler collapsed" 
        type="button" 
        onClick={toggleCollapse}
        aria-controls="navbarColor01" 
        aria-expanded={!isCollapsed} 
        aria-label="Toggle navigation"
      >
        <span className="navbar-toggler-icon"></span>
      </button>

      <div className={`navbar-collapse collapse ${!isCollapsed ? 'show' : ''}`} id="navbarColor01">
        <ul className="navbar-nav mr-auto">
          {!authService.isAuthenticated() && (
            <li className="nav-item">
              <Link className="nav-link" to="/signin">Sign In</Link>
            </li>
          )}
          {!authService.isAuthenticated() && (
            <li className="nav-item">
              <Link className="nav-link" to="/signup">Sign Up</Link>
            </li>
          )}
          {authService.isAuthenticated() && (
            <li className="nav-item">
              <a 
                className="nav-link" 
                onClick={logout}
              >
                Logout
              </a>
            </li>
          )}
          {authService.isAuthenticated() && (
            <li className={`nav-item dropdown ${isDropdownOpen ? 'show' : ''}`}>
              <a
                className="nav-link dropdown-toggle"
                onClick={toggleDropdown}
                aria-haspopup="true" 
                aria-expanded={isDropdownOpen}
              >
                Store
              </a>
              <div className={`dropdown-menu ${isDropdownOpen ? 'show' : ''}`}>
                <Link
                  className="dropdown-item"
                  to="/furniture/all"
                  onClick={() => setIsDropdownOpen(false)}
                >
                  All Furniture
                </Link>
                <Link
                  className="dropdown-item"
                  to="/furniture/user"
                  onClick={() => setIsDropdownOpen(false)}
                >
                  My Furniture
                </Link>
                <Link
                  className="dropdown-item"
                  to="/furniture/create"
                  onClick={() => setIsDropdownOpen(false)}
                >
                  Create
                </Link>
              </div>
            </li>
          )}
        </ul>
      </div>
    </nav>
  );
};

export default Navigation;
