// Client/src/app/authentication/signin/signin.component.ts
import { 
  Component, 
  OnInit, 
  ViewChild 
} from '@angular/core';
import { FormsModule, NgForm } from '@angular/forms';
import { AuthService } from '../auth.service';
import { Router } from '@angular/router';


@Component({
    selector: 'app-signin',
    templateUrl: './signin.component.html',
    styleUrls: ['./signin.component.css'],
    imports: [FormsModule]
})
export class SigninComponent implements OnInit {
  @ViewChild('loginForm') loginForm: NgForm;

  constructor(
    private authService : AuthService,
    private router: Router
  ) { }

  ngOnInit() {
  }

  signIn() {
    this.authService
      .login(this.loginForm.value)
      .subscribe((data: any) => {
        localStorage.setItem('token', data.accessToken);
        this.router.navigate([ '/home' ])
      });
  }

}

<div class="container">
  <h1>Sign In</h1>
  <form #loginForm="ngForm" (ngSubmit)="signIn()">
    <div class="form-group">
      <label for="email">Email</label>
      <input type="text" class="form-control" id="email"
        name="email"
        required
        email
        ngModel
        #email="ngModel">
        @if (email.invalid && email.touched) {
          <div class="alert alert-dark">
            Please provide a correct email address!
          </div>
        }
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          required
          minlength="4"
          ngModel
          #password="ngModel">
          @if (password.invalid && password.touched) {
            <div class="alert alert-dark">
              Password must have at least 4 characters
            </div>
          }
        </div>
        <button type="submit" class="btn btn-dark" [disabled]="loginForm.invalid">Sign In</button>
      </form>
    </div>

// Client-Vite/src/components/SignIn.tsx
import { useNavigate } from 'react-router';
import { Formik, Form, Field, ErrorMessage } from 'formik';
import * as Yup from 'yup';
import { authService } from '../services/authService';

const validationSchema = Yup.object({
  email: Yup.string()
    .required('Email is required')
    .email('Please provide a correct email address!'),
  password: Yup.string()
    .required('Password is required')
    .min(4, 'Password must have at least 4 characters')
});

interface SignInFormValues {
  email: string;
  password: string;
}

const SignIn = () => {
  const navigate = useNavigate();

  const initialValues: SignInFormValues = {
    email: '',
    password: ''
  };

  const handleSubmit = (values: SignInFormValues) => {
    authService.login(values)
      .then((response: any) => {
        localStorage.setItem('token', response.data.accessToken);
        navigate('/home');
      });
  };

  return (
    <div className="container">
      <h1>Sign In</h1>
      <Formik
        initialValues={initialValues}
        validationSchema={validationSchema}
        onSubmit={handleSubmit}
      >
        {({ isValid, dirty }) => (
          <Form>
            <div className="form-group">
              <label htmlFor="email">Email</label>
              <Field
                type="email"
                className="form-control"
                id="email"
                name="email"
                required
              />
              <ErrorMessage name="email">
                {msg => <div className="alert alert-dark">{msg}</div>}
              </ErrorMessage>
            </div>

            <div className="form-group">
              <label htmlFor="password">Password</label>
              <Field
                type="password"
                className="form-control"
                id="password"
                name="password"
                required
                minLength={4}
              />
              <ErrorMessage name="password">
                {msg => <div className="alert alert-dark">{msg}</div>}
              </ErrorMessage>
            </div>

            <button
              type="submit"
              className="btn btn-dark"
              disabled={!isValid || !dirty}
            >
              Sign In
            </button>
          </Form>
        )}
      </Formik>
    </div>
  );
};

export default SignIn;
