// Client-Vite/src/components/SignUp.tsx
import { useNavigate } from 'react-router';
import { Formik, Form, Field, ErrorMessage } from 'formik';
import * as Yup from 'yup';
import { authService } from '../services/authService';

const validationSchema = Yup.object({
  name: Yup.string()
    .required('Please provide your name!'),
  email: Yup.string()
    .required('Email is required')
    .email('Please provide a correct email address!'),
  password: Yup.string()
    .required('Password is required')
    .min(4, 'Password must have at least 4 characters!')
});

interface SignUpFormValues {
  name: string;
  email: string;
  password: string;
}

const SignUp = () => {
  const navigate = useNavigate();

  const initialValues: SignUpFormValues = {
    name: '',
    email: '',
    password: ''
  };

  const handleSubmit = (values: SignUpFormValues) => {
    authService.register(values)
      .then(() => {
        navigate('/signin');
      });
  };

  return (
    <div className="container">
      <h1>Sign Up</h1>
      <Formik
        initialValues={initialValues}
        validationSchema={validationSchema}
        onSubmit={handleSubmit}
      >
        {({ isValid, dirty }) => (
          <Form>
            <div className="form-group">
              <label htmlFor="name">Name</label>
              <Field
                type="text"
                className="form-control"
                id="name"
                name="name"
                required
              />
              <ErrorMessage name="name">
                {msg => <div className="alert alert-dark">{msg}</div>}
              </ErrorMessage>
            </div>

            <div className="form-group">
              <label htmlFor="email">Email</label>
              <Field
                type="email"
                className="form-control"
                id="email"
                name="email"
                required
              />
              <ErrorMessage name="email">
                {msg => <div className="alert alert-dark">{msg}</div>}
              </ErrorMessage>
            </div>

            <div className="form-group">
              <label htmlFor="password">Password</label>
              <Field
                type="password"
                className="form-control"
                id="password"
                name="password"
                required
                minLength={4}
              />
              <ErrorMessage name="password">
                {msg => <div className="alert alert-dark">{msg}</div>}
              </ErrorMessage>
            </div>

            <button
              type="submit"
              className="btn btn-dark"
              disabled={!isValid || !dirty}
            >
              Sign Up
            </button>
          </Form>
        )}
      </Formik>
    </div>
  );
};

export default SignUp;

// Client/src/app/authentication/signup/signup.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';
import { AuthService } from '../auth.service';
import { FormsModule, NgForm } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css'],
  imports: [FormsModule]
})
export class SignupComponent implements OnInit {
  @ViewChild('registerForm') registerForm: NgForm;

  constructor(
    private authService: AuthService,
    private router: Router
  ) { }

  ngOnInit() {
  }

  signUp() {
    this.authService
      .register(this.registerForm.value)
      .subscribe((data) => {
        this.router.navigate(['/signin']);
      });
  }
}

<div class="container">
  <h1>Sign Up</h1>
  <form (ngSubmit)="signUp()" #registerForm="ngForm">
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name"
        required
        ngModel
        #name="ngModel"
        name="name">

        @if (name.invalid && name.touched) {
          <div class="alert alert-dark">
            Please provide your name!
          </div>
        }
      </div>

      <div class="form-group">
        <label for="email">Email</label>
        <input type="text" class="form-control" id="email"
          required
          email
          ngModel
          #email="ngModel"
          name="email">

          @if (email.invalid && email.touched) {
            <div class="alert alert-dark">
              Please provide a correct email address!
            </div>
          }
        </div>

        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" class="form-control" id="password"
            required
            ngModel
            #password="ngModel"
            name="password"
            minlength="4">

            @if (password.invalid && password.touched) {
              <div class="alert alert-dark">
                Password must have at least 4 characters!
              </div>
            }
          </div>
          <button type="submit" class="btn btn-dark" [disabled]="registerForm.invalid">Sign Up</button>
        </form>
      </div>
